{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "example-service"
    },
    "spec": {
        "ports": [
            {
                "protocol": "TCP",
                "port": 80,
                "targetPort": 80
            }
        ]
    }
}